---
title: "WGCNA Trajectory Analysis on nanopore limb"
---

```{r}
library(ggplot2)
library(dplyr)
library(RColorBrewer)
library(data.table)
library(WGCNA)
options(stringsAsFactors = FALSE)
allowWGCNAThreads()
```
#Trajectory analysis on limb samples across age but bigger module size

```{r}
colours<- c("blue2","#FF7F0E","#2CA02C","#D62728","#9467BD","#9EDAE5","deepskyblue3","#BCBD22","#17BECF", "darkseagreen4",  "#AEC7E8", "#FFBB78",  "#98DF8A", "deepskyblue4", "#C5B0D5", "deepskyblue", "saddlebrown",  "#DBDB8D")
```

```{r}
#read promoter methylation file
prom_averag_meth <- read.csv("prom_averag_meth.csv")
#column name indicates sample ID (e.g., 182A) and animal age (e.g., 9.84)
```

```{r}
#read promoter methylation file in long format
meth_data_long <- read.csv("meth_data_long.csv")
#column All_clock indicate genes that appear in axolotl clock analysis on CpG sites
```

```{r}
#Preparing data
datMeth <- prom_averag_meth[,c(1:11)]
rownames(datMeth) <- datMeth[[1]]
datMeth <- datMeth[,-1]

gsg <- goodSamplesGenes(datMeth, verbose = 3)

datExpr <- t(datMeth) #transposing data

#preparing age data frame for the analysis
age <- data.frame(
  id = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10),
  Age = c(4, 9.84, 2.2, 4, 6.6, 0.73, 2.2, 9.84, 1.1, 6.6)
)
```

```{r}
gsg <- goodSamplesGenes(datExpr, verbose = 3)
gsg

datExpr<- datExpr[gsg$goodSamples, gsg$goodGenes]
```

```{r}
#Blockwise modules
net <- blockwiseModules(
  datExpr,
  power = 5,
  networkType = "signed",
  TOMType = "signed",
  minModuleSize = 1000,         
  reassignThreshold = 0,
  mergeCutHeight = 0.3,        
  numericLabels = TRUE,
  pamRespectsDendro = FALSE,
  deepSplit = 1,
  maxBlockSize = 38500,
  saveTOMs = FALSE,
  verbose = 4)

moduleColors <- labels2colors(net$colors, colorSeq = colours)
table(moduleColors)

moduleNumbers <- net$colors
table(moduleNumbers)
```

```{r}
#Dendrogram

pdf("WGCNA_dendrogram_18 modules.pdf", width = 60, height = 5)

  plotDendroAndColors(
    net$dendrograms[[b]],
    moduleColors,
    "Module Colors",
    main = paste("Module colours"),
    dendroLabels = FALSE,
    addGuide = TRUE,
    hang = 0.03,
    autoColorHeight = FALSE,
    colorHeight = 0.12)

dev.off()
```

```{r}
colorMap <- data.frame(
  module = unique(moduleNumbers),
  color = labels2colors(unique(moduleNumbers), colorSeq = colours)
)
colorMap

color_map <- setNames(colorMap$color, colorMap$module)
```

```{r}
#Module eigengenes and association with age

MEs <- net$MEs

#Ensure standard naming
MEs <- orderMEs(MEs)

#Correlate MEs with age
ageVec <- age[,2] 
MEcors <- cor(MEs, ageVec, use = "p")
MEpvals <- corPvalueStudent(MEcors, nSamples = length(ageVec))

#Adjust p-values (FDR)
MEpvals_FDR <- p.adjust(MEpvals, method = "fdr")
MEpvals_FDR
```

```{r}
#Make a summary table
moduleSummary <- data.frame(
  module = rownames(MEcors),
  module_number = as.numeric(gsub("^ME", "", rownames(MEcors))),
  cor_age = as.vector(MEcors),
  p_age = as.vector(MEpvals),
  FDR_age = as.vector(MEpvals_FDR),
  Value = 'Age Cor'
)

moduleSummary$symbol = ifelse(moduleSummary$p_age < 0.05, "*", "")
moduleSummary
```

```{r}
#Adding a dataframe that contains a list of module numbers and assigned colours
moduleMap <- unique(
  data.frame(
    ModuleNumber = moduleNumbers,
    ModuleColor  = moduleColors
  ))
```

```{r}
#Adding a dataframe that contains a list of module numbers and assigned age correlations
MEcors_col <- data.frame(
  ModuleNumber = as.numeric (gsub("^ME", "", rownames(MEcors))),
  MEcors)

MEcors_col <- left_join(MEcors_col, moduleMap, by='ModuleNumber')

rownames(MEcors_col) <- MEcors_col$ModuleColor
MEcors_col
```

```{r}
#Vector that contains age correlations and adding correlation values for each gene based on their module assignment
moduleAgeCor <- MEcors_col$MEcors
names(moduleAgeCor) <- MEcors_col$ModuleColor

geneAgeCor <- moduleAgeCor[moduleColors]
```

```{r}
traitColors <- numbers2colors(
  geneAgeCor,
  signed = TRUE,
  lim = c(-1, 1),
  colors = blueWhiteRed(50))
```

```{r}
#Dendrogram with correlation and modules

png("WGCNA_dendrogram_18 modules_traits.pdf", width = 60, height = 9, units = "in",
  res = 300, bg='transparent')

 plotDendroAndColors(
    net$dendrograms[[b]],
    cbind(moduleColors, traitColors),
    groupLabels = c("Module", "Age correlation"),
    dendroLabels = FALSE,
    addGuide = TRUE,
    hang = 0.03,
    autoColorHeight = FALSE,
    cex.colorLabels = 2.7, #labels for coloured strips below the dendrogram
    cex.lab = 3,           
    cex.axis = 2.8, 
    main = NULL,
    colorHeight = 0.33 #size of colour legend
  )

dev.off()
```

```{r}
#Extracting the assigned modules
moduleData <- data.frame(
  feature = colnames(datExpr),    
  WGCNA_module = net$colors)
```

```{r}
#Preparing data for plotting to visualise ageing trajectories
module_long <- meth_data_long 
module_long <- right_join(module_long, moduleData, by= c('gene_id' = 'feature'))
```

```{r}
ggplot(module_long, aes(x = Age_com, y = Methylation_mean_per_age, group = gene_id, color = as.factor(WGCNA_module), fill = as.factor(WGCNA_module))) +
      facet_wrap(~WGCNA_module, nrow=2) +
 geom_line(alpha = 0.1, size=0.1) +
stat_summary(aes(group = WGCNA_module), fun = mean, geom = "line", size = 1.1, color = 'black') +
    geom_vline(xintercept = 2, linetype = "dashed", color = "black", size = 0.5, alpha = 0.6) +
    geom_vline(xintercept = 4, linetype = "dashed", color = "black", size = 0.5, alpha = 0.6) +
  scale_color_manual(values = color_map) +
  geom_text(data = module_long %>% distinct(gene_id, WGCNA_module) %>%
  count(WGCNA_module, name = "n_genes"),
            aes(x = 5, y = Inf, label = paste0("n = ", n_genes)),
           vjust = 1.2, size = 3.5, color = "black", fontface='bold', inherit.aes = FALSE) +
          labs(fill = "Module", x = 'Age', y= "Methylation", title = 'WGCNA module-based clustering') +
          theme_minimal() +
          scale_x_continuous (breaks = 1:10) +
          theme(panel.border = element_rect(size = 0.2, color = "black", fill = NA), legend.position = "none", 
  strip.text = element_text(size = 15), axis.text = element_text(size = 11), axis.title = element_text(size = 13), axis.ticks = element_line(size = 0.2, color = "black"), panel.grid = element_blank()
                )

ggsave('18 modules_WGCNA module-based clustering of nanopore promoters.png', width=13, height=3.3, dpi=300, bg='transparent')
```

```{r}
#Plot clock genes based on trajectories
ggplot(module_long %>% filter (All_Clock=='Yes'), aes(x = Age_com, y = Methylation_mean_per_age, group = gene_id, color = as.factor(WGCNA_module))) +
 geom_line(alpha = 0.6, size=0.35) +
        facet_wrap(~WGCNA_module, nrow=3) +
stat_summary(aes(group = WGCNA_module), fun = mean, geom = "line", size = 1.1, color = 'black') +
    geom_vline(xintercept = 2, linetype = "dashed", color = "black", size = 0.5, alpha = 0.6) +
    geom_vline(xintercept = 4, linetype = "dashed", color = "black", size = 0.5, alpha = 0.6) +
   scale_color_manual(values = color_map) +
  geom_text(data = module_long %>% filter (All_Clock=='Yes') %>% distinct(gene_id, WGCNA_module) %>%
  count(WGCNA_module, name = "n_genes"),
            aes(x = 5, y = Inf, label = paste0("n = ", n_genes)),
           vjust = 1.2, size = 3, color = "black", inherit.aes = FALSE) +
          labs(fill = "Module", x = 'Age', y= "Methylation", title = 'WGCNA module-based clustering of array/clock genes') +
          theme_minimal() +
          scale_x_continuous (breaks = 1:10) +
          theme(panel.border = element_rect(size = 0.2, color = "black", fill = NA), legend.position = "none",
  strip.text = element_text(size = 13), axis.text = element_text(size = 10), axis.title = element_text(size = 11), axis.ticks = element_line(size = 0.2, color = "black"), panel.grid = element_blank())

ggsave('18 modules_WGCNA module-based clustering of nanopore promoters_clock_array genes.png', width=10, height=4, dpi=300)
```

```{r}
clock_array_genes <- intersect(prom_averag_meth$gene_id[prom_averag_meth$All_Clock=='Yes'], rownames(datMeth))

# Get module assignment per gene
featureModules <- moduleColors
names(featureModules) <- colnames(datExpr)  # colnames(datExpr) = rownames(datMeth)

# Subset to features in WGCNA
isClock <- names(featureModules) %in% clock_array_genes
modules <- unique(featureModules)
```

```{r}
enrichResults <- lapply(modules, function(mod) {
  inMod <- featureModules == mod
  # 2x2 table: in module vs not, clock vs non-clock
  a <- sum(inMod & isClock)
  b <- sum(inMod & !isClock)
  c <- sum(!inMod & isClock)
  d <- sum(!inMod & !isClock)
  mat <- matrix(c(a, b, c, d), nrow = 2,
                dimnames = list(Clock = c("Clock", "NonClock"),
                                Module = c("InModule", "NotInModule")))

  ft <- fisher.test(mat)
  data.frame(
    module = mod,
    clock_in_module = a,
    nonclock_in_module = b,
    clock_not_module = c,
    nonclock_not_module = d,
    odds_ratio_clock_enr = ft$estimate,
    p_clock_enr = ft$p.value,
    clock_enr = 'Clock promoters enrichment'
  )
})

enrichDF <- do.call(rbind, enrichResults)
rownames(enrichDF) <- unique(net$colors)  #assigning correct module names
enrichDF$module_number <- as.numeric(rownames(enrichDF))
enrichDF$FDR_enr <- p.adjust(enrichDF$p_clock_enr, method = "fdr")
enrichDF$clock_proportion <- enrichDF$clock_in_module / (enrichDF$clock_in_module + enrichDF$nonclock_in_module)
enrichDF
```

```{r}
#Table to save with results

table_WGCNA_modules <- left_join(moduleSummary[,c(2:5)], enrichDF[,c(2,3,6,7,9, 10)], by= 'module_number')

table_WGCNA_modules$n_features <- table_WGCNA_modules$clock_in_module + table_WGCNA_modules$nonclock_in_module

table_WGCNA_modules <- table_WGCNA_modules[,-6]
colnames(table_WGCNA_modules)[colnames(table_WGCNA_modules) == "module_number"] <- "ModuleID"
table_WGCNA_modules <- table_WGCNA_modules[c(1, 9, 2:8)] 

write.csv(table_WGCNA_modules, "table_wgcna_18_modules.csv", row.names = FALSE)
```
